/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health
         * @description Report that the HTTP application is ready to accept requests.
         */
        get: operations["health_api_v1_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login */
        post: operations["login_api_v1_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Logout */
        post: operations["logout_api_v1_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Me */
        get: operations["me_api_v1_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/organizations/proposals": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Propose Organization */
        post: operations["propose_organization_api_v1_organizations_proposals_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/organizations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Organizations */
        get: operations["list_organizations_api_v1_organizations_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/organizations/{organization_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Organization */
        get: operations["get_organization_api_v1_organizations__organization_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/organizations/{organization_id}/versions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Organization Versions */
        get: operations["list_organization_versions_api_v1_organizations__organization_id__versions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/organizations/{organization_id}/versions/{spec_version_id}/confirm": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Confirm Organization Version */
        post: operations["confirm_organization_version_api_v1_organizations__organization_id__versions__spec_version_id__confirm_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/organizations/{organization_id}/versions/{spec_version_id}/publish": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Publish Organization Version */
        post: operations["publish_organization_version_api_v1_organizations__organization_id__versions__spec_version_id__publish_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runtime/bindings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Runtime Bindings */
        get: operations["list_runtime_bindings_api_v1_runtime_bindings_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runtime/bindings/{binding_key}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Put Runtime Binding */
        put: operations["put_runtime_binding_api_v1_runtime_bindings__binding_key__put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runtime/controls": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Runtime Controls */
        get: operations["get_runtime_controls_api_v1_runtime_controls_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/organizations/{organization_id}/tasks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Submit Task */
        post: operations["submit_task_api_v1_organizations__organization_id__tasks_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tasks/{task_id}/plan": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Plan Task */
        post: operations["plan_task_api_v1_tasks__task_id__plan_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tasks/{task_id}/start": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Start Task */
        post: operations["start_task_api_v1_tasks__task_id__start_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tasks/{task_id}/inputs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Upload Task Input */
        post: operations["upload_task_input_api_v1_tasks__task_id__inputs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tasks/{task_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Task */
        get: operations["get_task_api_v1_tasks__task_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tasks/{task_id}/artifacts/{artifact_id}/content": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Task Artifact Content */
        get: operations["get_task_artifact_content_api_v1_tasks__task_id__artifacts__artifact_id__content_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tasks/{task_id}/usage": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Task Token Usage */
        get: operations["get_task_token_usage_api_v1_tasks__task_id__usage_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tasks/{task_id}/retry": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Retry Failed Task */
        post: operations["retry_failed_task_api_v1_tasks__task_id__retry_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tasks/{task_id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Cancel Task */
        post: operations["cancel_task_api_v1_tasks__task_id__cancel_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tasks/{task_id}/approvals": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Task Approvals */
        get: operations["list_task_approvals_api_v1_tasks__task_id__approvals_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tasks/{task_id}/approvals/{approval_id}/decision": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Decide Task Approval */
        post: operations["decide_task_approval_api_v1_tasks__task_id__approvals__approval_id__decision_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tasks/{task_id}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Stream Task Events */
        get: operations["stream_task_events_api_v1_tasks__task_id__events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AgentRoleSpec
         * @description One persistent formal role in an organization definition.
         */
        AgentRoleSpec: {
            /** Role Key */
            role_key: string;
            /** Name */
            name: string;
            /** Responsibility */
            responsibility: string;
            /**
             * Is Lead
             * @default false
             */
            is_lead: boolean;
            /** Reports To */
            reports_to?: string | null;
            /** Runtime Binding Key */
            runtime_binding_key: string;
        };
        /**
         * ApprovalDecision
         * @enum {string}
         */
        ApprovalDecision: "accept" | "decline" | "cancel";
        /** ApprovalDecisionRequest */
        ApprovalDecisionRequest: {
            decision: components["schemas"]["ApprovalDecision"];
        };
        /**
         * ApprovalKind
         * @enum {string}
         */
        ApprovalKind: "command_execution" | "file_change";
        /** ApprovalResponse */
        ApprovalResponse: {
            /** Approval Id */
            approval_id: string;
            /** Task Id */
            task_id: string;
            /** Assignment Id */
            assignment_id: string;
            /** Runtime Execution Id */
            runtime_execution_id: string;
            /** Provider */
            provider: string;
            kind: components["schemas"]["ApprovalKind"];
            status: components["schemas"]["ApprovalStatus"];
            /** Thread Id */
            thread_id: string;
            /** Turn Id */
            turn_id: string;
            /** Item Id */
            item_id: string;
            /** Reason */
            reason: string | null;
            /** Command */
            command: string | null;
            /** Cwd */
            cwd: string | null;
            /** Details */
            details: {
                [key: string]: unknown;
            };
            decision: components["schemas"]["ApprovalDecision"] | null;
            /** Decided By User Id */
            decided_by_user_id: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Decided At */
            decided_at: string | null;
        };
        /**
         * ApprovalStatus
         * @enum {string}
         */
        ApprovalStatus: "pending" | "accepted" | "declined" | "cancelled";
        /** ArtifactInputBindingResponse */
        ArtifactInputBindingResponse: {
            /** Input Binding Id */
            input_binding_id: string;
            /** Artifact Id */
            artifact_id: string;
            /** Consumer Workspace Id */
            consumer_workspace_id: string;
            /** Materialized Relative Path */
            materialized_relative_path: string;
            /** Artifact Sha256 */
            artifact_sha256: string;
            status: components["schemas"]["ArtifactInputBindingStatus"];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Revoked At */
            revoked_at: string | null;
        };
        /**
         * ArtifactInputBindingStatus
         * @enum {string}
         */
        ArtifactInputBindingStatus: "materialized" | "revoked";
        /** ArtifactResponse */
        ArtifactResponse: {
            /** Artifact Id */
            artifact_id: string;
            /** Origin */
            origin: string;
            /** Source Delivery Id */
            source_delivery_id: string;
            /** Producer Assignment Id */
            producer_assignment_id: string | null;
            /** Producer Plan Step Id */
            producer_plan_step_id: string | null;
            /** Source Workspace Id */
            source_workspace_id: string | null;
            /** Contract Key */
            contract_key: string;
            /** Schema Version */
            schema_version: string;
            /** Artifact Version */
            artifact_version: number;
            /** Media Type */
            media_type: string;
            /** File Name */
            file_name: string;
            /** Storage Relative Path */
            storage_relative_path: string;
            /** Sha256 */
            sha256: string;
            /** Byte Size */
            byte_size: number;
            status: components["schemas"]["ArtifactStatus"];
            /** Validation Summary */
            validation_summary: string | null;
            /** Supersedes Artifact Id */
            supersedes_artifact_id: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Released At */
            released_at: string | null;
            /** Content Url */
            content_url: string;
            /** Download Url */
            download_url: string;
        };
        /**
         * ArtifactStatus
         * @enum {string}
         */
        ArtifactStatus: "draft" | "validated" | "released" | "rejected" | "superseded";
        /** AssignmentResponse */
        AssignmentResponse: {
            /** Assignment Id */
            assignment_id: string;
            /** Assignment Key */
            assignment_key: string;
            /** Assignment Kind */
            assignment_kind: string;
            /** Agent Role Key */
            agent_role_key: string;
            /** Instructions */
            instructions: string;
            /** Acceptance Criteria */
            acceptance_criteria: string;
            /** Execution Id */
            execution_id: string;
            /** Plan Step Id */
            plan_step_id: string | null;
            status: components["schemas"]["AssignmentStatus"];
            /** Result Summary */
            result_summary: string | null;
            runtime_execution: components["schemas"]["RuntimeExecutionResponse"] | null;
        };
        /**
         * AssignmentStatus
         * @enum {string}
         */
        AssignmentStatus: "pending" | "submitted" | "running" | "waiting" | "completed" | "failed" | "cancelled";
        /** AssignmentTokenUsageResponse */
        AssignmentTokenUsageResponse: {
            /** Assignment Id */
            assignment_id: string;
            /** Assignment Key */
            assignment_key: string;
            /** Assignment Kind */
            assignment_kind: string;
            /** Agent Role Key */
            agent_role_key: string;
            /** Runtime Execution Id */
            runtime_execution_id: string;
            /** Execution Id */
            execution_id: string;
            /** Provider */
            provider: string;
            /** Requested Model */
            requested_model: string | null;
            /** Actual Model */
            actual_model: string | null;
            execution_status: components["schemas"]["RuntimeExecutionStatus"];
            /** Usage Status */
            usage_status: string;
            /** Reserved Tokens */
            reserved_tokens: number;
            /** Charged Tokens */
            charged_tokens: number | null;
            /** Input Tokens */
            input_tokens: number | null;
            /** Cached Input Tokens */
            cached_input_tokens: number | null;
            /** Output Tokens */
            output_tokens: number | null;
            /** Reasoning Output Tokens */
            reasoning_output_tokens: number | null;
            /** Total Tokens */
            total_tokens: number | null;
        };
        /** ErrorEnvelope */
        ErrorEnvelope: {
            /** Code */
            code: string;
            /** Message */
            message: string;
            /** Request Id */
            request_id: string;
            /** Details */
            details?: unknown | null;
        };
        /** HealthResponse */
        HealthResponse: {
            /**
             * Status
             * @constant
             */
            status: "ok";
            /** Service */
            service: string;
            /** Environment */
            environment: string;
        };
        /** LoginRequest */
        LoginRequest: {
            /** Username */
            username: string;
            /**
             * Password
             * Format: password
             */
            password: string;
        };
        /** LoginResponse */
        LoginResponse: {
            user: components["schemas"]["UserResponse"];
        };
        /** OrganizationDetailResponse */
        OrganizationDetailResponse: {
            /** Organization Id */
            organization_id: string;
            /** Name */
            name: string;
            /** Description */
            description: string;
            /** Current Published Version Id */
            current_published_version_id: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            current_published_spec: components["schemas"]["OrganizationSpec"] | null;
        };
        /** OrganizationProposalRequest */
        OrganizationProposalRequest: {
            /** Organization Id */
            organization_id?: string | null;
            /** Source Request */
            source_request?: string | null;
            spec: components["schemas"]["OrganizationSpec"];
        };
        /**
         * OrganizationSpecV1
         * @description A versioned, portable organization definition for the V1 tree model.
         */
        OrganizationSpec: {
            /**
             * Schema Version
             * @default 1.0
             * @constant
             */
            schema_version: "1.0";
            /** Name */
            name: string;
            /**
             * Description
             * @default
             */
            description: string;
            /** Roles */
            roles: components["schemas"]["AgentRoleSpec"][];
        };
        /** OrganizationSummaryResponse */
        OrganizationSummaryResponse: {
            /** Organization Id */
            organization_id: string;
            /** Name */
            name: string;
            /** Description */
            description: string;
            /** Current Published Version Id */
            current_published_version_id: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** OrganizationVersionResponse */
        OrganizationVersionResponse: {
            /** Spec Version Id */
            spec_version_id: string;
            /** Organization Id */
            organization_id: string;
            /** Version Number */
            version_number: number;
            status: components["schemas"]["OrganizationVersionStatus"];
            spec: components["schemas"]["OrganizationSpec"];
            /** Source Request */
            source_request: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Confirmed At */
            confirmed_at: string | null;
            /** Published At */
            published_at: string | null;
        };
        /**
         * OrganizationVersionStatus
         * @enum {string}
         */
        OrganizationVersionStatus: "proposal" | "confirmed" | "published" | "superseded" | "archived";
        /** PlanStepResponse */
        PlanStepResponse: {
            /** Plan Step Id */
            plan_step_id: string;
            /** Step Key */
            step_key: string;
            /** Role Key */
            role_key: string;
            /** Step Kind */
            step_kind: string;
            /** Sequence */
            sequence: number;
            /** Objective */
            objective: string;
            /** Acceptance Criteria */
            acceptance_criteria: string;
            /** Input Contracts */
            input_contracts: string[];
            /** Output Contracts */
            output_contracts: {
                [key: string]: unknown;
            }[];
            /** Dependency Step Ids */
            dependency_step_ids: string[];
            status: components["schemas"]["PlanStepStatus"];
            /** Assignment Id */
            assignment_id: string | null;
            /** Input Bindings */
            input_bindings: components["schemas"]["ArtifactInputBindingResponse"][];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Ready At */
            ready_at: string | null;
            /** Completed At */
            completed_at: string | null;
        };
        /**
         * PlanStepStatus
         * @enum {string}
         */
        PlanStepStatus: "pending_dependency" | "ready" | "submitted" | "running" | "waiting" | "validating_output" | "completed" | "blocked" | "failed" | "cancelled";
        /** RuntimeBindingResponse */
        RuntimeBindingResponse: {
            /** Runtime Binding Id */
            runtime_binding_id: string;
            /** Binding Key */
            binding_key: string;
            /** Provider */
            provider: string;
            /** Model */
            model: string | null;
            /** Reasoning Effort */
            reasoning_effort: string | null;
            security_mode: components["schemas"]["RuntimeSecurityMode"];
            /** Is Active */
            is_active: boolean;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** RuntimeBindingUpsertRequest */
        RuntimeBindingUpsertRequest: {
            /** Provider */
            provider: string;
            /** Model */
            model?: string | null;
            /** Reasoning Effort */
            reasoning_effort?: string | null;
            security_mode: components["schemas"]["RuntimeSecurityMode"];
        };
        /** RuntimeControlResponse */
        RuntimeControlResponse: {
            /** Provider */
            provider: string;
            /** Max Concurrent Executions */
            max_concurrent_executions: number;
            /** Active Executions */
            active_executions: number;
            /** Token Budget Limit */
            token_budget_limit: number | null;
            /** Token Reservation Per Execution */
            token_reservation_per_execution: number | null;
            /** Tokens Reserved */
            tokens_reserved: number;
            /** Tokens Consumed */
            tokens_consumed: number;
            /** Tokens Remaining */
            tokens_remaining: number | null;
            /** Provider Capacity Status */
            provider_capacity_status: string;
            /** Provider Capacity Reason */
            provider_capacity_reason: string | null;
            /** Provider Capacity Resets At */
            provider_capacity_resets_at: string | null;
            /** Provider Capacity Observed At */
            provider_capacity_observed_at: string | null;
        };
        /** RuntimeExecutionResponse */
        RuntimeExecutionResponse: {
            /** Runtime Execution Id */
            runtime_execution_id: string;
            /** Execution Id */
            execution_id: string;
            /** Provider */
            provider: string;
            /** Runtime Binding Id */
            runtime_binding_id: string | null;
            /** Runtime Binding Key */
            runtime_binding_key: string | null;
            /** Requested Model */
            requested_model: string | null;
            /** Actual Model */
            actual_model: string | null;
            /** Reasoning Effort */
            reasoning_effort: string | null;
            /** Security Mode */
            security_mode: string | null;
            /** Approval Policy */
            approval_policy: string | null;
            /** Sandbox Mode */
            sandbox_mode: string | null;
            /** Network Access */
            network_access: boolean | null;
            status: components["schemas"]["RuntimeExecutionStatus"];
            /** Runtime Job Id */
            runtime_job_id: string | null;
            /** Thread Id */
            thread_id: string | null;
            /** Turn Id */
            turn_id: string | null;
            /** Workspace Id */
            workspace_id: string | null;
            /** Result Summary */
            result_summary: string | null;
            /** Wait Reason */
            wait_reason: string | null;
            /** Reserved Tokens */
            reserved_tokens: number;
            /** Charged Tokens */
            charged_tokens: number | null;
            /** Usage Status */
            usage_status: string;
            /** Input Tokens */
            input_tokens: number | null;
            /** Cached Input Tokens */
            cached_input_tokens: number | null;
            /** Output Tokens */
            output_tokens: number | null;
            /** Reasoning Output Tokens */
            reasoning_output_tokens: number | null;
            /** Total Tokens */
            total_tokens: number | null;
            /** Context Compactions */
            context_compactions: number;
        };
        /**
         * RuntimeExecutionStatus
         * @enum {string}
         */
        RuntimeExecutionStatus: "submitted" | "running" | "waiting" | "completed" | "failed" | "cancelled";
        /**
         * RuntimeSecurityMode
         * @description Named product security profiles compiled into Runtime-specific policy.
         * @enum {string}
         */
        RuntimeSecurityMode: "demo_full_access" | "workspace_restricted";
        /** TaskCreateRequest */
        TaskCreateRequest: {
            /** Request */
            request: string;
            /** @default legacy */
            orchestration_mode: components["schemas"]["TaskOrchestrationMode"];
        };
        /** TaskExecutionPlanResponse */
        TaskExecutionPlanResponse: {
            /** Plan Id */
            plan_id: string;
            /** Plan Version */
            plan_version: number;
            /** Schema Version */
            schema_version: string;
            /** Definition Hash */
            definition_hash: string;
            /** Source */
            source: string;
            status: components["schemas"]["TaskExecutionPlanStatus"];
            /** Summary */
            summary: string;
            /** Validation Summary */
            validation_summary: string | null;
            /** Initial Input Contracts */
            initial_input_contracts: string[];
            /** Steps */
            steps: components["schemas"]["PlanStepResponse"][];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Activated At */
            activated_at: string | null;
            /** Completed At */
            completed_at: string | null;
        };
        /**
         * TaskExecutionPlanStatus
         * @enum {string}
         */
        TaskExecutionPlanStatus: "draft" | "validated" | "active" | "completed" | "needs_revision" | "failed" | "cancelled";
        /** TaskInputArtifactRequest */
        TaskInputArtifactRequest: {
            /** Contract Key */
            contract_key: string;
            /**
             * Schema Version
             * @default 1.0
             */
            schema_version: string;
            /** Media Type */
            media_type: string;
            /** File Name */
            file_name: string;
            /** Content Base64 */
            content_base64: string;
            /** Source Delivery Id */
            source_delivery_id: string;
        };
        /**
         * TaskOrchestrationMode
         * @description Select the compatibility workflow or the planned linear workflow.
         * @enum {string}
         */
        TaskOrchestrationMode: "legacy" | "planned";
        /** TaskResponse */
        TaskResponse: {
            /** Task Id */
            task_id: string;
            /** Organization Id */
            organization_id: string;
            /** Organization Spec Version Id */
            organization_spec_version_id: string;
            /** Request */
            request: string;
            orchestration_mode: components["schemas"]["TaskOrchestrationMode"];
            status: components["schemas"]["TaskStatus"];
            /** Result Summary */
            result_summary: string | null;
            /** Assignments */
            assignments: components["schemas"]["AssignmentResponse"][];
            execution_plan: components["schemas"]["TaskExecutionPlanResponse"] | null;
            /** Artifacts */
            artifacts: components["schemas"]["ArtifactResponse"][];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Completed At */
            completed_at: string | null;
        };
        /**
         * TaskStatus
         * @enum {string}
         */
        TaskStatus: "created" | "planning" | "running" | "waiting" | "needs_revision" | "completed" | "failed" | "cancelled";
        /** TaskTokenUsageResponse */
        TaskTokenUsageResponse: {
            /** Task Id */
            task_id: string;
            /** Execution Count */
            execution_count: number;
            /** Reported Execution Count */
            reported_execution_count: number;
            /** Unavailable Execution Count */
            unavailable_execution_count: number;
            /** Pending Execution Count */
            pending_execution_count: number;
            /** Reserved Tokens */
            reserved_tokens: number;
            /** Charged Tokens */
            charged_tokens: number;
            /** Input Tokens */
            input_tokens: number;
            /** Cached Input Tokens */
            cached_input_tokens: number;
            /** Output Tokens */
            output_tokens: number;
            /** Reasoning Output Tokens */
            reasoning_output_tokens: number;
            /** Observed Total Tokens */
            observed_total_tokens: number;
            /** Assignments */
            assignments: components["schemas"]["AssignmentTokenUsageResponse"][];
        };
        /** UserResponse */
        UserResponse: {
            /** User Id */
            user_id: string;
            /** Username */
            username: string;
            /** Display Name */
            display_name: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_api_v1_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    login_api_v1_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoginResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    logout_api_v1_auth_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    me_api_v1_auth_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    propose_organization_api_v1_organizations_proposals_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OrganizationProposalRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrganizationVersionResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    list_organizations_api_v1_organizations_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrganizationSummaryResponse"][];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    get_organization_api_v1_organizations__organization_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                organization_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrganizationDetailResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    list_organization_versions_api_v1_organizations__organization_id__versions_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                organization_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrganizationVersionResponse"][];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    confirm_organization_version_api_v1_organizations__organization_id__versions__spec_version_id__confirm_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                organization_id: string;
                spec_version_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrganizationVersionResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    publish_organization_version_api_v1_organizations__organization_id__versions__spec_version_id__publish_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                organization_id: string;
                spec_version_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrganizationVersionResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    list_runtime_bindings_api_v1_runtime_bindings_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RuntimeBindingResponse"][];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    put_runtime_binding_api_v1_runtime_bindings__binding_key__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                binding_key: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RuntimeBindingUpsertRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RuntimeBindingResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    get_runtime_controls_api_v1_runtime_controls_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RuntimeControlResponse"];
                };
            };
        };
    };
    submit_task_api_v1_organizations__organization_id__tasks_post: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": string;
            };
            path: {
                organization_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TaskCreateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Too Many Requests */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    plan_task_api_v1_tasks__task_id__plan_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                task_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Too Many Requests */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    start_task_api_v1_tasks__task_id__start_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                task_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Too Many Requests */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    upload_task_input_api_v1_tasks__task_id__inputs_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                task_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TaskInputArtifactRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ArtifactResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Too Many Requests */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    get_task_api_v1_tasks__task_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                task_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Too Many Requests */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    get_task_artifact_content_api_v1_tasks__task_id__artifacts__artifact_id__content_get: {
        parameters: {
            query?: {
                download?: boolean;
            };
            header?: never;
            path: {
                task_id: string;
                artifact_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Verified immutable Artifact content. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/octet-stream": string;
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Too Many Requests */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    get_task_token_usage_api_v1_tasks__task_id__usage_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                task_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskTokenUsageResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Too Many Requests */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    retry_failed_task_api_v1_tasks__task_id__retry_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                task_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Too Many Requests */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    cancel_task_api_v1_tasks__task_id__cancel_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                task_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Too Many Requests */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    list_task_approvals_api_v1_tasks__task_id__approvals_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                task_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApprovalResponse"][];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Too Many Requests */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    decide_task_approval_api_v1_tasks__task_id__approvals__approval_id__decision_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                task_id: string;
                approval_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ApprovalDecisionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApprovalResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Too Many Requests */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    stream_task_events_api_v1_tasks__task_id__events_get: {
        parameters: {
            query?: never;
            header?: {
                "Last-Event-ID"?: string | null;
            };
            path: {
                task_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Too Many Requests */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
}
